version: '2'
services:
  php:
    build: .
    command: ["/var/www/bin/wait-for-it", "-t", "60", "postgres:5432", "--", "/var/www/bin/install"]
    ports:
      - "80:80"
    depends_on:
      - postgres
    volumes:
      - ./html:/var/www/html

  postgres:
    image: postgres:9.6.2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: www
      POSTGRES_PASSWORD: root
